### ISSUE TITLE
Warns

### ISSUE THREAD

**Issue by awinogradov** [bem-contrib/bem-forms#171]
We need methods to check form-field content. If input doesn't exist in form-field_type_input we should send warn.

**Comment by adinvadim** [comment]
https://github.com/bem-contrib/bem-forms/blob/v1.0.0/common.blocks%2Fform-field%2Fform-field.browser.js#L14
we have already done it or not?

**Comment by awinogradov** [comment]
@adinvadim looks like yes ;)
