### ISSUE TITLE
move form-field_name_myName to data-bem props

### ISSUE THREAD

**Issue by voischev** [bem-contrib/bem-forms#173]
Есть какой то смысл в физическом классе на элементе кроме как "удобно к нему обратиться" ? 

Выглядит не красиво. Более красиво брать имя из `this.props.name` 

Что думаете?

**Comment by zxqfox** [comment]
Имя надо брать явно не из класса, но классы нужны для филдов.

**Comment by voischev** [comment]
@zxqfox какие именно классы?

**Comment by awinogradov** [comment]
Это надо для поиска филдов. В противном случае искать филды по имени будет не эффективно. Сейчас это обычный `.findBlockInside`, а если унести в data-bem то это будет долгий перебор живого DOM.

**Comment by awinogradov** [comment]
В `props.name` имя таки есть ;) Можно брать.

**Comment by voischev** [comment]
мне просто не нравится наличие не красивого класса

**Comment by awinogradov** [comment]
Таки не нравится не смотри)))

**Comment by voischev** [comment]
Жаль что долгий перебор в этом случае тоже есть... только под капотом :( https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L342-L378

**Comment by awinogradov** [comment]
Так там обычный селектор. А тут придется выбрать все и внутри каждой искать. Селектор не построишь ;(

**Comment by voischev** [comment]
```js
let name = 'cool';
form.getFields().forEach(field => field.params.name === name? field: null);
```
оно же кажется даже быстрее будет

**Comment by zxqfox** [comment]
Можно подумать про data-name атрибут

**Comment by awinogradov** [comment]
Можно думать асинхронно)

**Comment by voischev** [comment]
@kompolom @zxqfox а может всетаки лучше в this.params?
посмотрел измененный код в PR. Кажется смысла обращаться в дом там нет.

+ 1 PR не убирает предыдущее поведение

**Comment by kompolom** [comment]
@voischev теперь убирает.

**Comment by zxqfox** [comment]
@voischev Были кейсы, которые могли поменять филды, и в этом случае форма будет работать не с теми филдами, то есть будет ошибка. Давай пока не оптимизировать.
