### ISSUE TITLE
Add mods invalid, dirty, for controls to the deps

### ISSUE THREAD

**Issue by adinvadim** [bem-contrib/bem-forms#185]
It will be unnecessary?

https://github.com/bem-contrib/bem-forms/blob/v1.0.0/common.blocks%2Fform-field%2F_type%2Fform-field_type_input.deps.js

```
{
    shouldDeps : {
        block : 'input',
        mods : { invalid : true, dirty : true }
    }
}
```

**Comment by awinogradov** [comment]
@adinvadim PR?)
