### ISSUE TITLE
Avoid `name` modifier usage

### ISSUE THREAD

**Issue by JiLiZART** [bem-contrib/bem-forms#198]
When i set `name` for `form-field` as `form[_username]`, so
`bem-core` can't properly parse value of `name` mod on `form-field` (cuz it's not valid class name by spec).
Maybe better way to store `name` as `js` param and not as mod.

**Comment by awinogradov** [comment]
yep. We know this problem ;( Simple names only

**Comment by JiLiZART** [comment]
Fixed in 1.0.0
