### ISSUE TITLE
Не хватает версии в package.json

### ISSUE THREAD

**Issue by kompolom** [bem-contrib/bem-forms#221]
npm отказывается устанавливать пакет без поля version

**Comment by awinogradov** [comment]
https://github.com/bem-contrib/bem-forms/blob/v2.0.0/package.json#L3

**Comment by kompolom** [comment]
@awinogradov речь о ветке 1.0.0

**Comment by awinogradov** [comment]
Так давай PR?)

**Comment by zzzaaa** [comment]
ребзя, в package.json всего 2-а MUST поля: name и version.
Без них это просто набор мета данных, который невозможно проинсталить через npm.
Это прискорбно.
